### ISSUE TITLE
Support for pid services

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon-extensions-if#19]
Support for PID services to serve DatONE, starting with Handle and EZID

**Comment by lstillwe** [comment]
Hey Mike,

I am not sure how to build the sub modules with the parent jargon-pom.
How does that work - especially in eclipse?

Thanks,
Lisa

On Feb 14, 2017, at 2:14 PM, Mike Conway <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #19<https://github.com/DICE-UNC/jargon-extensions-if/issues/19> to @lstillwe<https://github.com/lstillwe>.

**Comment by michael-conway** [comment]
It should be exactly the same.  Is something going wrong?

**Comment by lstillwe** [comment]
Thanks for responding.

Here is what I am seeing:

cd jargon-extensions-if/
dhcp152-54-9-71:jargon-extensions-if lisa$ mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.irods.jargon:jargon-extensions-if:[unknown-version]: Could not find artifact org.irods:jargon-pom:pom:4.2.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 8, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.irods.jargon:jargon-extensions-if:[unknown-version] (/Users/lisa/Documents/workspace-sts-3.8.3.RELEASE/jargon-extensions-if/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.irods.jargon:jargon-extensions-if:[unknown-version]: Could not find artifact org.irods:jargon-pom:pom:4.2.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 8, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
dhcp152-54-9-71:jargon-extensions-if lisa$


Thanks,
Lisa

On Feb 15, 2017, at 7:39 AM, John Constable <notifications@github.com<mailto:notifications@github.com>> wrote:

It should be exactly the same. Is something going wrong?
